language: java
jdk: openjdk11
deploy:
  provider: heroku
  api_key:
    secure: WWK+li4TIONsWyzZf9Y3DKTbpfxkQxrwYaMxeRAY0oWV0Ip+zWk34I30CQ5Ru0GVwmotHn1qhteh0lDmmbZf08Gbg4zJbL/0HlbJ4Z1bzSVH9RutJM7foCnLqnrLMQ1P6Qswh06YRVtatzcTq187D38BrOgb5T2T4wRnDFvN/6dt37+8zaUqswTHNeU02CPjJS3PeQIJpuoFSmmI5YBtHH7jBM5cQBWtxWWyVloRmPGCkev+/stcIaj+uVCWPhT5GJGQqrcRt37iV2nIz1C+MA0CRxSOg4e9Sg9wYi/7jgm7EwArXfDoTo3CXWCJryNlOWk5Dzy7dNshwC2Y1zCfP6xRgHvh2tnEyXQ2TiqotCr0DwrEYsoowv3LjPDBlmov6wjuGZAmks+TVk53lhbQpGEBFsjDwtZa7gy07DSu4nqRSXsCrxxD3L/Int4h06Ca+P7BAWKKrOguR2Pjsrhi8FP0E8EQLB5y2BNkW0ZSHNuKeKIlhTS0CrVovIW9UR4LtA3gz4i4X6bPzp5VgRMFOJ6EDQ/aKq+PETfVlfxGBzUHOkMRVMRjYGySyFIKqM2QW9S0UNZ3L/yvOTyBwzgWRKw1b71trAcVxh+6o8YJ/cUk5ARi1orQ9RGYjMFyHgQDgrKSy4TpDuqbtivhJNwGWDL03GNuESL1BkUIFQxcYnE=
  app: cmsvkapp
  on:
    repo: vla-parfenkov/cms_res_vkapp_back
